http:
  routers:
    uniconn-api:
      rule: "Host(`localhost`)"
      service: uniconn-api-service
      entryPoints:
        - web

  services:
    uniconn-api-service:
      loadBalancer:
        servers:
          - url: "http://uniconn-api:8080"
