#This is for local testing
version: "3.9"

services:
  api:
    build:
      context: ../../uniconn-backend/backend
      dockerfile: Dockerfile
    container_name: uniconn-api
    ports:
      - "8080:8080"
    env_file:
      - ../../uniconn-backend/.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: uniconn-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../uniconn-backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db-data:
