version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uniconn
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../../backend
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: uniconn
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pg-local:
