global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "traefik"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "uniconn_api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]